service: warpDeskBooking

image: sdoering/vml-warp

servers:
  web:
    - 116.203.36.121

proxy: 
  ssl: true
  host: deskbooking.vml.one
  app_port: 8000

registry:
  server: ghcr.io
  username:
    - DOCKER_REGISTRY_TOKEN
  password:
    - DOCKER_REGISTRY_TOKEN

builder:
  arch: amd64

env:
  secret:
    - WARP_SECRET_KEY
  clear:
    WARP_DATABASE: "sqlite:////opt/warp/data/warp.db"

volumes:
  - /var/lib/warp/data:/opt/warp/data

hooks:
  pre-deploy:
    remote:
      - mkdir -p /var/lib/warp/data
      - chown -R 1002:1002 /var/lib/warp/data
      - chmod 755 /var/lib/warp/data