service: warpDeskBooking

image: sdoering/vml-warp

servers:
  web:
    - 116.203.36.121

proxy: 
  ssl: true
  host: deskbooking.vml.one
  app_port: 8000

registry:
  server: ghcr.io
  username:
    - DOCKER_REGISTRY_TOKEN
  password:
    - DOCKER_REGISTRY_TOKEN

healthcheck:
  path: /
  port: 8000
  max_attempts: 10
  interval: 5

builder:
  arch: amd64

env:
  secret:
    - WARP_SECRET_KEY
  clear:
    WARP_DATABASE: "sqlite:////opt/warp/data/warp.db"

volumes:
  - /var/lib/warp/data:/opt/warp/data
