service: warpDeskBooking

image: sdoering/vml-warp

servers:
  web:
    - 116.203.36.121

proxy: 
  ssl: true
  host: deskbooking.vml.one
  app_port: 8000

registry:
  server: ghcr.io
  username:
    - DOCKER_REGISTRY_TOKEN
  password:
    - DOCKER_REGISTRY_TOKEN

builder:
  arch: amd64

env:
  secret:
    - WARP_SECRET_KEY 
    - WARP_ADMIN_USER
    - WARP_ADMIN_PASSWORD
  clear:
    WARP_DATABASE: "sqlite:////opt/warp/data/warp.db"
    WARP_DATABASE_INIT_SCRIPT: '["/opt/warp/sql/sqlite_schema.sql"]'
    WARP_FORCE_ADMIN_UPDATE: 'true'

volumes:
  - /var/lib/warp/data:/opt/warp/data:rw,Z